art_gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home_page.urls')),
    path('aboutus/', include('about_page.urls')),
    path('products/', include('products.urls')),
    path('gallery_bag/', include('gallery_bag.urls')),
    path('search_product/', include('search_product.urls')),
    path('checkout/', include('checkout.urls')),
    path('profiles/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path
from contact.views import (Contact, Thank_You)
urlpatterns = [
    path("", Contact.as_view(), name="contact"),
    path('thankyou/', Thank_You.as_view(), name='thankyou'),
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('category_paintings', views.category_paintings,
         name='category_paintings'),
    path('add_category/', views.add_category, name='add_category'),
    path('edit_category/<int:categoriesgroup_id>/', views.edit_category,
         name='edit_category'),
    path('delete_category/<int:categoriesgroup_id>/', views.delete_category,
         name='delete_category'),
    path('detail/<int:product_id>', views.product_detail,
         name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product,
         name='delete_product'),
]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    full_name = models.CharField(max_length=50, null=False, blank=False)
    user_profile = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="orders",
    )
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    county = models.CharField(max_length=80, null=True, blank=True)
    country = CountryField(blank_label="Country *", null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0
    )
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0
    )
    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0
    )
    original_bag = models.TextField(null=False, blank=False, default="")
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default=""
    )

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = (
            self.lineitems.aggregate(Sum("lineitem_total"))["lineitem_total__sum"] or 0 # noqa
        )
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = (
                self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
            )
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(
        Order,
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        related_name="lineitems",
    )
    product = models.ForeignKey(
        Product, null=False, blank=False, on_delete=models.CASCADE
    )
    product_size = models.CharField(
        max_length=10, null=False, blank=False
    )  # frame sizes
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, blank=False, editable=False
    )

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f"SKU {self.product.sku} on order {self.order.order_number}"

products/models.py
from django.db import models
from cloudinary.models import CloudinaryField


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = CloudinaryField('image')

    def __str__(self):
        return self.name


class CategoriesGroups(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    friendly_name = models.CharField(max_length=254, null=True, blank=True)
    image = CloudinaryField('image')

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Category, CategoriesGroups


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    image = forms.ImageField(label='Image', required=False,
                             widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'


class CategoryForm(forms.ModelForm):

    class Meta:
        model = CategoriesGroups
        fields = '__all__'

    image = forms.ImageField(label='Image', required=False,
                             widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-0'

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower

from .models import Product, Category, CategoriesGroups
from .forms import ProductForm, CategoryForm

# Create your views here.


def all_products(request):
    """ A view to show all products, including sorting and search queries """
    # <Model>.objects.all()
    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request,
                               "You didn't enter any search criteria!")
                return redirect(reverse('products'))

            queries = Q(name__icontains=query) | Q(description__icontains=query) # noqa
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to show individual product details """

    product = get_object_or_404(Product, pk=product_id)

    context = {
        'product': product,
    }

    return render(request, 'products/product_detail.html', context)


def category_paintings(request):
    """ A view to return the category painting page """
    categoriesgroups = CategoriesGroups.objects.all()

    context = {
        "categoriesgroups": categoriesgroups,
    }

    return render(request, 'products/category_paintings.html', context)

# CRUD managements for category in Category Painting page


@login_required
def add_category(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('category_paintings'))

    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save()
            messages.success(request, 'Successfully added category!')
            return redirect(reverse('category_paintings'))
        else:
            messages.error(request,
                           'Failed to add product.',
                           'Please ensure the form is valid.')
    else:
        form = CategoryForm()

    template = 'products/add_category.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_category(request, categoriesgroup_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('category_paintings'))

    category = get_object_or_404(CategoriesGroups, pk=categoriesgroup_id)
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('edit_category', args=[category.id]))
        else:
            messages.error(request,
                           'Failed to update product.',
                           'Please ensure the form is valid.')
    else:
        form = CategoryForm(instance=category)
        messages.info(request, f'You are editing {category.name}')

    template = 'products/edit_category.html'
    context = {
        'form': form,
        'category': category,
    }

    return render(request, template, context)


@login_required
def delete_category(request, categoriesgroup_id):
    """ Delete a product from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('category_paintings'))

    category = get_object_or_404(CategoriesGroups, pk=categoriesgroup_id)
    category.delete()
    messages.success(request, 'Category deleted!')
    return redirect(reverse('category_paintings'))


# CRUD managements for Products
@login_required
def add_product(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request,
                           'Failed to add product.',
                           'Please ensure the form is valid.')
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(request,
                           'Failed to update product.',
                           'Please ensure the form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """ Delete a product from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))

products/templates/products/add_category.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container px-4">
    <div class="row">
        <div class="col-12">
            <h2 class="logo-font display-4 mb-4 text-center">Add Category Management</h2>
            <h5 class="text-muted">Add Category</h5>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <form method="POST" action="{% url 'add_category' %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name != 'image' %}
                    {{ field | as_crispy_field }}
                {% else %}
                    {{ field }}
                {% endif %}
                {% endfor %}
                <div class="text-right mt-3">
                    <a class="btn rounded-0 mb-2" href="{% url 'category_paintings' %}">Cancel</a>
                    <button class="btn rounded-0 mb-2" type="submit">Add Category</button>
                </div>
            </form>
        </div>
    </div>
</div>
<footer></footer>
{% endblock %}
{% block postloadjs %}
{{ block.super }}
<script type="text/javascript">
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container px-4">
    <div class="row">
        <div class="col-12">
            <h2 class="logo-font display-4 mb-4 text-center">Art Gallery Management</h2>
            <h5 class="text-muted">Add a Art Gallery</h5>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name != 'image' %}
                    {{ field | as_crispy_field }}
                {% else %}
                    {{ field }}
                {% endif %}
                {% endfor %}
                <div class="text-right mt-3">
                    <a class="btn rounded-0 mb-2" href="{% url 'products' %}">Cancel</a>
                    <button class="btn rounded-0 mb-2" type="submit">Add Art Gallery</button>
                </div>
            </form>
        </div>
    </div>
</div>
<footer></footer>
{% endblock %}
{% block postloadjs %}
{{ block.super }}
<script type="text/javascript">
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

products/templates/products/category_paintings.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col text-center mt-3">
            <h3 class=" display-4 logo-font p-3">Category Painting</h3>
            <hr class="w-100 mb-3">
        </div>
        {% if request.user.is_superuser %}
            <div class="col-12 text-right">
                <form method="POST" action="{% url 'add_category' %}" class="form mb-2" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                    {% if field.name != 'image' %}
                    {{ field | as_crispy_field }}
                    {% else %}
                    {{ field }}
                    {% endif %}
                    {% endfor %}
                    <div class="text-right mt-3">
                        <button class="btn rounded-0" type="submit">Add category</button>
                    </div>
                </form>
            </div>
        {% endif %}
    </div>
<div class="row">
    <div class="product-container col-10 offset-1">
        <div class="row mt-1 mb-4"></div>
        <div class="row">
            {% for categoriesgroup in categoriesgroups %}
            <div class="col-xl-4 col-xl-2 mb-3">
                <div class="card h-100 border-0">
                    {% if categoriesgroup.image %}
                    <img class="card-img-top img-fluid" src="{{ categoriesgroup.image.url }}" loading="lazy" alt="{{ categoriesgroup.name }}">
                    {% else %}
                    <img class="card-img-top img-fluid shadow p-2 mb-5 bg-body rounded" src="https://res.cloudinary.com/dhl4uxgix/image/upload/v1699216440/noimage_v16ou9.png" loading="lazy" alt="No image on the display as mute photo image">
                    {% endif %}
                    <div class="card-footer pt-0 border-0 text-left">
                        <div class="row">
                            <div class="col mt-0">
                            <div class="card-body mt-0">
                                <h5 class="card-title">{{ categoriesgroup.name }}</h5>
                                <p class="card-text p_white">{{categoriesgroup.description}}</p>
                                {% if categoriesgroup.category %}
                                    <div class="d-flex justify-content-center">
                                        <a class="btn btn_ligth rounded-0 mt-1" href="{% url 'products' %}?category={{ categoriesgroup.category.name }}">{{ categoriesgroup.name }}</a>
                                    {% endif %}
                                    </div>
                                </div>
                            </div>
                            {% if request.user.is_superuser %}
                            <small class="ml-3">
                                <div class="d-flex justify-content-between">
                                    <a class="btn btn_ligth rounded-0 mt-1" href="{% url 'edit_category' categoriesgroup.id %}">Edit</a> |
                                    <a class="btn btn_ligth rounded-0 mt-1" href="{% url 'delete_category' categoriesgroup.id %}">Delete</a>
                                </div>
                            </small>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
</div>
<footer></footer>
{% endblock %}

products/templates/products/edit_category.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container px-4">
    <div class="row">
        <div class="col-12">
            <h2 class="logo-font display-4 text-center">Edit Category Management</h2>
            <h5 class="text-muted">Edit a category</h5>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <form method="POST" action="{% url 'edit_category' category.id %}" class="form mb-2"
                enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                <div class="mt-4"></div>
                    {% if field.name != 'image' %}
                    <div class="mt-4"></div>
                    {{ field | as_crispy_field }}
                {% else %}
                <div class="mt-4"></div>
                    {{ field }}
                {% endif %}
                {% endfor %}
                <div class="text-right">
                    <a class="btn rounded-0 mb-2" href="{% url 'category_paintings' %}">back to category painting</a>
                    <button class="btn rounded-0 mb-2" type="submit">Update category</button>
                </div>
            </form>
        </div>
    </div>
</div>
<footer></footer>
{% endblock %}
{% block postloadjs %}
{{ block.super }}
<script type="text/javascript">
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container px-4">
    <div class="row">
        <div class="col-12">
            <h2 class="logo-font display-4 text-center">Art Gallery Management</h2>
            <h5 class="text-muted">Edit a art gallery</h5>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2"
                enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name != 'image' %}
                    {{ field | as_crispy_field }}
                {% else %}
                    {{ field }}
                {% endif %}
                {% endfor %}
                <div class="text-right">
                    <a class="btn btn-outline-black rounded-0 mb-2" href="{% url 'products' %}">Cancel</a>
                    <button class="btn btn-black rounded-0 mb-2" type="submit">Update art gallery</button>
                </div>
            </form>
        </div>
    </div>
</div>
<footer></footer>
{% endblock %}
{% block postloadjs %}
{{ block.super }}
<script type="text/javascript">
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container p-4 mt-5">
    <div class="row">
        <div class="col text-center mt-3">
            <h3 class="display-4 logo-font p-3">Add to bag</h3>
            <hr class="w-100 mb-3">
        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <div class="col-12 col-lg-6">
            <div class="image-container my-5">
                {% if product.image %}
                <a href="{{ product.image.url }}" target="_blank">
                    <img class="card-img-top img-fluid" src="{{ product.image.url }}" loading="lazy" alt="{{ product.name }}">
                </a>
                {% else %}
                <a href="">
                    <img class="card-img-top img-fluid shadow p-2 mb-5 bg-body rounded" src="https://res.cloudinary.com/dhl4uxgix/image/upload/v1699216440/noimage_v16ou9.png" loading="lazy" alt="No image on the display as mute photo image">
                </a>
                {% endif %}
            </div>
        </div>
        <div class="col-12 col-lg-6 d-flex justify-content-start">
            <div class="product-details-container ps-4 mb-5 mt-md-5">
                <p class="p_dark mb-0">{{ product.name }}</p>
                <p class="p_dark lead mb-0 font-weight-bold">&#8364;{{ product.price }}</p>
                {% if product.category %}
                <p class="small mt-1 mb-0">
                    <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
                        <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                    </a>
                </p>
                {% endif %}
                <p class="mt-3 p_dark">{{ product.description }}</p>
                <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-row">
                        {% with product.has_sizes as s %}
                        {% if s %}
                        <div class="col-12">
                            <p class="p_dark"><strong>Size:</strong></p>
                            <select class="form-control rounded-0 w-50" name="product_size" id='id_product_size'>
                                <option value='6"x8"'>6"x8"</option>
                                <option value='8"x10"'>8"x10"</option>
                                <option value='11"x14"' selected>11"x14"</option>
                                <option value='12"x14"'>12"x14"</option>
                                <option value='16"x16"'>16"x16"</option>
                                <option value='16"x18"'>16"x18"</option>
                                <option value='16"x20"'>16"x20"</option>
                            </select>
                        </div>
                        {% endif %}
                        <div class="col-12">
                            <p class="mt-3 p_dark"><strong>Quantity:</strong></p>
                            <div class="form-group w-100">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <button class="decrement-qty btn rounded-0" data-item_id="{{ product.id }}"
                                            id="decrement-qty_{{ product.id }}">
                                            <span class="icon">
                                                <i class="fas fa-minus"></i>
                                            </span>
                                        </button>
                                    </div>
                                    <input class="form-control qty_input" type="number" name="quantity" value="1" min="1"
                                        max="99" data-item_id="{{ product.id }}" id="id_qty_{{ product.id }}">
                                    <div class="input-group-append">
                                        <button class="increment-qty btn rounded-0" data-item_id="{{ product.id }}"
                                            id="increment-qty_{{ product.id }}">
                                            <span class="icon">
                                                <i class="fas fa-plus"></i>
                                            </span>
                                        </button>
                                    </div>
                                    {% if request.user.is_superuser %}
                                    <small class="ml-3 w-100">
                                        <div class= "mt-2 d-flex justify-content-between">
                                        <a class="btn rounded-0 me-5" href="{% url 'edit_product' product.id %}">Edit</a>
                                        <a class="btn rounded-0 ms-2" href="{% url 'delete_product' product.id %}">Delete</a>
                                        </div>
                                    </small>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
        
                        <div class="col{% if s %}-12 mt-2{% endif %}">
                            <a href="{% url 'products' %}" class="btn rounded-0 mt-5">
                                <span class="icon">
                                    <i class="fas fa-chevron-left"></i>
                                </span>
                                <span class="text-uppercase">Keep Shopping</span>
                            </a>
                            <input type="submit" class="btn rounded-0 text-uppercase mt-5" value="Add to Bag">
                        </div>
                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                        {% endwith %}
                    </div>
                </form>
            </div>
        </div>
    </div>    
</div>
<footer></footer>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}